[package]
name = "channels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bus = "2.4.0"
crossbeam = "0.8.2"
may = "0.3.42"
throttle = "0.1.0"
